"""add document version uniqueness constraint

Revision ID: 8293c85f2162
Revises: 69fe9b3e5d90
Create Date: 2026-08-12 08:49:42.299240

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8293c85f2162"
down_revision: str | Sequence[str] | None = "69fe9b3e5d90"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_document_version_number",
        "document_versions",
        ["document_id", "version_number"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_document_version_number", "document_versions", type_="unique"
    )
    # ### end Alembic commands ###
